### ISSUE TITLE
Feature Request: Support shortcuts for the prefire menu

### ISSUE THREAD

**Issue by ReneRebsdorf** [lengran/OpenPrefirePrac#14]
In the interest of improve user experience, by reducing the number of clicks needed between practice runs, I suggest the following is implemented, instead of the current:

!prefire
!1
!3

I suggest adding support for:

- .map anubis ([CHR15cs](https://github.com/CHR15cs) does this and without having to provide de_ as part of the map names)
- .prefire set 1
- .prefire mode random
- .prefire mode all
- .prefire difficulty 0-6 (or maybe use 'level' instead of difficulty as it may be easier to spell for some?)
- .prefire lang en/pl/cn/da/de/etc.

**Comment by lengran** [comment]
Thanks for the suggestion. I'll do this and will let you know when I finish.

**Comment by lengran** [comment]
Done. Try [this](https://github.com/lengran/OpenPrefirePrac/actions/runs/8788064219) build.

**Comment by ReneRebsdorf** [comment]
> Done. Try [this](https://github.com/lengran/OpenPrefirePrac/actions/runs/8788064219) build.

Seems to work great :-)
Only tested it for a few minutes, I will be away most of this week, but if I get time I can test it some more.

Some feedback:

- Not sure on the intuitiveness of 'mp' and 'hd' for naming of map and the difficulty respectively, but it provides the desired feature, so I am happy
- The shortcut menu is a bit difficult to 'find' it seems like at the moment you have to type something starting with !prefire before it gives you the correct syntax, this is probably resolved if you intend on updating the "main menu" description, I can help with this if you want.
- The description of the shortcut menu is good: very easy to understand how to use it

**Comment by lengran** [comment]
Thanks. Take your time. The next release should be in this weekend so there's a lot of time. I'll test it as much as I can as well. As for the feedback, here are my thoughts:
- I agree with you. The intuitiveness needs to be improved definitely. I'll change *mp* into *map* then since one letter doesn't make too much difference on making it short. Would *df* be better than *hd*(I was thinking about the word hardness which itself is not really proper in such situation)? What's your first thought about the abbreviation of "difficulty"? 
- The usage section in README will be updated as soon as the abbreviation is decided. Also it will be included in the release note.  I do have implement a *!prefire help* but it is also a "something start with !prefire". So I guess we do need to update the main menu. Will a "type *!prefire help* for usage of shortcut commands" do it? It can be attached to the bottom of the menu.

**Comment by ReneRebsdorf** [comment]
So in terms of shortcuts, I think the primary win is from not having to provide multiple commands, and not so much how short the text is in each command, although leaning against common practices of 2-4 letters seems like a good idea. (e.g. your use of the abbreviation 'prac' for one of the commands, and this repo)

I now see where you were going with hd, although as you mention, it doesn't quite work for this context.

I was thinking of whether or not df might be a good idea, was also thinking of diff, although that leans too much towards "difference", which may increase confusing again.

"lvl" could also be used, but that might confuse with the "prac" command.

So in the end, I asked chatGPT for inspiration....
I'll boil the back and forth prompt down: It suggested df for 2 letters, and diff for 4 letters.

My suggestion based on the above is thus to use the following:

- prac
- map
- df
- mode

The help-text will resolve any confusion, and after a single use, people will learn the commands :-)

**Comment by lengran** [comment]
So it's decided. [This test build](https://github.com/lengran/OpenPrefirePrac/actions/runs/8799817242) contains all the changes we discussed. If nothing goes wrong, this will be included in next release.
