### ISSUE TITLE
[Feature] Raw Bot Difficulty levels

### ISSUE THREAD

**Issue by mavproductions** [lengran/OpenPrefirePrac#17]
Hey @lengran!

Wondering if you've had a chance to look at [these workshop maps](https://steamcommunity.com/workshop/filedetails/?id=3244203953) popping up.

One thing I really like about these maps is that the bots have very specific bot difficulty levels. On Hell mode, it appears if you walk into their line-of-sight whatsoever, they just insta-kill you after .5 milliseconds or so.

It would be really neat if such a feature could be added to openprefireprac, as it would add more granular control over difficulty.

Thanks for considering!

**Comment by lengran** [comment]
I have been doing research on this for the last half month. These maps are using different behavior tree to achieve that, which I have tried to implement. Unluckily, due to the lack of document and reference material, the script I wrote still contains some issues and it requires more time to solve them. That's why in the upcoming release a CSS based aim lock method is provided to strengthen the bots temporarily. I'll definitely keep working on this continuously and see if I can find a work around.

For now in multiplayer scenario, I suggest you to tune the bots' reaction time by editing the botprofile.db, which is much easier to do and achieves similar effects. For your reference, you can check [this](https://www.reddit.com/r/GlobalOffensive/comments/16u8175/rename_bots_in_cs2/?rdt=32930) for the way to customize botprofile.db on your server. And here's a [post](https://api.xiaoheihe.cn/maxnews/app/share/detail/3003654) written in Chinese describing several ways of modifying bots' difficulty in details, including ways to edit botprofile.db.

For single player use, the maps provided by 5E are pretty cool. Though I have only tried the mirage one, but I believe they will keep releasing new maps until achieve a full coverage of the competitive map pool.

**Comment by mavproductions** [comment]
Lovely response. I'm happy I can have that workaround to test for now. I figured maps had different behavioral trees available, as plugins might also have different behavioral trees as well available.

Power to you to keep ironing out this option. Take all the time you need 🙂

**Comment by lengran** [comment]
Here's the botprofile.db I'm using, which is good enough for me for now. Hope this could save you some time if you need it.

[botprofile.zip](https://github.com/lengran/OpenPrefirePrac/files/15325425/botprofile.zip)

**Comment by lengran** [comment]
A simple bot behavior tree based implement has been released. Thanks to 5EPlay for their inspiring prefire workshop maps. The behavior tree files are extracted from these maps.
