### ISSUE TITLE
Bots are often looking in the wrong direction

### ISSUE THREAD

**Issue by ReneRebsdorf** [lengran/OpenPrefirePrac#18]
I suspect the reason bots are often looking in the wrong direction is due to the positions being re-used across multiple practice sets/sessions?

Would it perhaps be easier to both have optimal angle for all positions + easier to make new templates that the "dual use of the same position" concept is removed, in favor of some duplication?

I hope my suggestion makes sense, essentially I am asking whether the benefit of the first line in each txt file, e.g. "b_apts a_palace a_ramp mid_to_b b_retake" in maps/de_mirage/under_to_jungle.txt is better than simply duplicating the positions into individual .txt files, where we then have a single file for each practice set? (I know, I know - we all hate duplication, but readability is often the only valid counterargument I find)

**Comment by lengran** [comment]
The first line is not positive reuse. It's the list of incompatible practices. The purpose is to avoid interference in multiplayer practice scenarios, e.g. people being shot by bots of another practice, or bots of one practice being killed by players on other practices.

As for the reason of bots looking away from indicated angles, I suspect that it's the navigation info on the map. This can be fixed by using a customized behavior tree. I have been working on that these days but I still have some problems to figure out for now.

**Comment by lengran** [comment]
By the way, next release contains a naive implementation of bots always looking at players. The release should be out in a day or two.

**Comment by ReneRebsdorf** [comment]
Awesome, thank you for the quick reply
I'll be looking forward to the update 

I need to mess around a bit with the multiplayer option 😊
