### ISSUE TITLE
Unable to automatically string prefire arenas together?

### ISSUE THREAD

**Issue by ImWanamaker** [lengran/OpenPrefirePrac#9]
trying to setup a personal prefire server and I appreciate what you guys have made here.

Just wondering if there is a way to automatically string together arenas. For example, once a aps has been cleared it then puts you into the banana to b arena.

Sorry if this isn't the place for this. New to github and can't find a wiki for this plugin anywhere

**Comment by lengran** [comment]
If what you want is to automatically start a new practice every time a previous one is finished, it it not a feature that I have implemented and it is not planed to be implement as well. Because from my perspective I can't see it generally needed. I'm sorry for that.

But in general I'm open to this idea. If this is a common need (please leave a message here if you also want that feature), I might be able to do that in the future.

Feel free to discuss about how you want the project to be. All suggestions are welcomed.

**Comment by alt-plus-f4** [comment]
i can implement this if you still want it.

**Comment by lengran** [comment]
> trying to setup a personal prefire server and I appreciate what you guys have made here.
> 
> Just wondering if there is a way to automatically string together arenas. For example, once a aps has been cleared it then puts you into the banana to b arena.
> 
> Sorry if this isn't the place for this. New to github and can't find a wiki for this plugin anywhere

BTW, you can type ! + number to switch to other practices after you finish a practice. The menu doesn't close itself after you choose one option. This is not really automatically as you described but still quite convenient.
